name: BukkitLightLevel
version: 1.2
api-version: 1.18
author: Craig McDaniel
website: https://github.com/cpmcdaniel/bukkit-light-level
main: org.kowboy.bukkit.light.LightLevelPlugin

permissions:
  light-level:
    # Permissions are not yet implemented.
    description: Allows use of the light-level features
    default: op

