name: LightLevel
version: 1.0
api-version: 1.15
author: Craig McDaniel
website: https://github.com/cpmcdaniel/bukkit-light-level
main: org.kowboy.bukkit.light.LightLevelPlugin

commands:
  light-level:
    description: Turns the light-level effects on/off
    aliases: [light, ll]
    usage: /light-level [on/off]
    permission: light-level
    permission-message: You don't have permission light-level

permissions:
  light-level:
    # Permissions are not yet implemented.
    description: Allows execution of light-level command.
    default: op

